comp_opt=-gnatq -gnatQ -O1 -gnatafo -fdata-sections -ffunction-sections
bind_opt=-E
link_opt=-Wl,--gc-sections
gnatmake_opt=-g
gnatfind_opt=-rf
cross_prefix=
remote_machine=
debug_cmd=${cross_prefix}gdb ${main}
main=sonja3test
build_dir=~/MMS/programs-PC/
check_cmd=${cross_prefix}gnatmake -u -c -gnatc ${gnatmake_opt} ${full_current} -cargs ${comp_opt}
make_cmd=${cross_prefix}gnatmake -o ${main} ${main} ${gnatmake_opt} -cargs ${comp_opt} -bargs ${bind_opt} -largs ${link_opt}
comp_cmd=${cross_prefix}gnatmake -u -c ${gnatmake_opt} ${full_current} -cargs ${comp_opt}
run_cmd=./${main}
src_dir=./luthien/
src_dir=/home/jan/MMS/programs-PC/silmaril/
obj_dir=/home/jan/MMS/programs-PC/obj/
debug_pre_cmd=cd ${build_dir}
debug_post_cmd=
