/*	Proview V5.1.0 pwr_systemclasses.h */

/*	Generated by co_convert. */
/*	Do not edit this file. */

#ifndef pwr_systemclasses_h
#define pwr_systemclasses_h

#ifndef pwr_class_h
#include "pwr_class.h"
#endif



#ifndef pwr_cClass_Alias
#define pwr_cClass_Alias 65904UL

/*_* Class: Alias
    Body:  SysBody
    @Aref Alias pwr_sClass_Alias
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tObjid                          Object pwr_dAlignW;
} pwr_sClass_Alias;

#endif


#ifndef pwr_cClass_Appl
#define pwr_cClass_Appl 65792UL

/*_* Class: Appl
    Body:  SysBody
    @Aref Appl pwr_sClass_Appl
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tString256                      FileName pwr_dAlignW;
  pwr_tString40                       ProgramName pwr_dAlignW;
  pwr_tBoolean                        StartWithDebug pwr_dAlignW;
  pwr_tBoolean                        Load pwr_dAlignW;
  pwr_tBoolean                        Run pwr_dAlignW;
  pwr_tBoolean                        KernelMode pwr_dAlignW;
  pwr_tInt32                          KernelStackSize pwr_dAlignW;
  pwr_tInt32                          JobPriority pwr_dAlignW;
  pwr_tInt32                          ProcessPriority pwr_dAlignW;
  pwr_tString256                      Arg pwr_dAlignW;
} pwr_sClass_Appl;

#endif


#ifndef pwr_cClass_Attribute
#define pwr_cClass_Attribute 65576UL

/*_* Class: Attribute
    Body:  SysBody
    @Aref Attribute pwr_sClass_Attribute
*/

typedef struct {
  pwr_tPgmName                        PgmName pwr_dAlignLW;
  pwr_tInt32                          Type pwr_dAlignW;
  pwr_tUInt32                         Offset pwr_dAlignW;
  pwr_tUInt32                         Size pwr_dAlignW;
  pwr_tAdefFlags                      Flags pwr_dAlignW;
  pwr_tUInt32                         Elements pwr_dAlignW;
  pwr_tUInt32                         ParamIndex pwr_dAlignW;
  pwr_tTypeId                         TypeRef pwr_dAlignW;
  pwr_tInt32                          Filler pwr_dAlignW;
} pwr_sClass_Attribute;

#endif


#ifndef pwr_cClass_AttrXRef
#define pwr_cClass_AttrXRef 65848UL

/*_* Class: AttrXRef
    Body:  SysBody
    @Aref AttrXRef pwr_sClass_AttrXRef
*/

typedef struct {
  pwr_tPgmName                        PgmName pwr_dAlignLW;
  pwr_tInt32                          Type pwr_dAlignW;
  pwr_tUInt32                         Offset pwr_dAlignW;
  pwr_tUInt32                         Size pwr_dAlignW;
  pwr_tAdefFlags                      Flags pwr_dAlignW;
  pwr_tUInt32                         Elements pwr_dAlignW;
  pwr_tUInt32                         ParamIndex pwr_dAlignW;
  pwr_tXRef                           Identity pwr_dAlignW;
  pwr_tXRef                           Source pwr_dAlignW;
  pwr_tXRef                           Target pwr_dAlignW;
  pwr_tUInt32                         XRefType pwr_dAlignW;
} pwr_sClass_AttrXRef;

#endif


#ifndef pwr_cClass_Bit
#define pwr_cClass_Bit 66024UL

/*_* Class: Bit
    Body:  SysBody
    @Aref Bit pwr_sClass_Bit
*/

typedef struct {
  pwr_tString80                       Text pwr_dAlignLW;
  pwr_tString32                       PgmName pwr_dAlignW;
  pwr_tUInt32                         Value pwr_dAlignW;
} pwr_sClass_Bit;

#endif


#ifndef pwr_cClass_Buffer
#define pwr_cClass_Buffer 65608UL

/*_* Class: Buffer
    Body:  SysBody
    @Aref Buffer pwr_sClass_Buffer
*/

typedef struct {
  pwr_tPgmName                        PgmName pwr_dAlignLW;
  pwr_tInt32                          Type pwr_dAlignW;
  pwr_tUInt32                         Offset pwr_dAlignW;
  pwr_tUInt32                         Size pwr_dAlignW;
  pwr_tAdefFlags                      Flags pwr_dAlignW;
  pwr_tUInt32                         Elements pwr_dAlignW;
  pwr_tUInt32                         ParamIndex pwr_dAlignW;
  pwr_tClassId                        Class pwr_dAlignW;
} pwr_sClass_Buffer;

#endif


#ifndef pwr_cClass_ClassDef
#define pwr_cClass_ClassDef 65544UL

/*_* Class: ClassDef
    Body:  SysBody
    @Aref ClassDef pwr_sClass_ClassDef
*/

typedef struct {
  pwr_tInt32                          Editor pwr_dAlignLW;
  pwr_tInt32                          Method pwr_dAlignW;
  pwr_tClassDefFlags                  Flags pwr_dAlignW;
  pwr_tUInt32                         NumOfObjBodies pwr_dAlignW;
  pwr_tInt32                          PopEditor pwr_dAlignW;
  pwr_tInt32                          Filler pwr_dAlignW;
} pwr_sClass_ClassDef;

#endif


#ifndef pwr_cClass_ClassHier
#define pwr_cClass_ClassHier pwr_eCix_ClassHierUL

#endif


#ifndef pwr_cClass_ClassLost
#define pwr_cClass_ClassLost pwr_eCix_ClassLostUL

#endif


#ifndef pwr_cClass_ClassVolume
#define pwr_cClass_ClassVolume 65952UL

/*_* Class: ClassVolume
    Body:  SysBody
    @Aref ClassVolume pwr_sClass_ClassVolume
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tObjectIx                       NextOix pwr_dAlignW;
  pwr_tUInt32                         RtVersion pwr_dAlignW;
  pwr_tTime                           RtCreTime pwr_dAlignLW;
  pwr_tString16                       RtCreator pwr_dAlignW;
  pwr_tUInt32                         RtCardinality pwr_dAlignW;
  pwr_tUInt32                         RtBodySize pwr_dAlignW;
  pwr_tObjectIx                       NextCix pwr_dAlignW;
  pwr_tObjectIx                       NextTix[16] pwr_dAlignW;
  pwr_tUInt32                         DvVersion pwr_dAlignW;
  pwr_tConfigStatusEnum               ConfigurationStatus pwr_dAlignW;
} pwr_sClass_ClassVolume;

#endif


#ifndef pwr_cClass_CreateVolume
#define pwr_cClass_CreateVolume 65976UL

/*_* Class: CreateVolume
    Body:  SysBody
    @Aref CreateVolume pwr_sClass_CreateVolume
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tVolumeId                       Volume pwr_dAlignW;
} pwr_sClass_CreateVolume;

#endif


#ifndef pwr_cClass_DbCallBack
#define pwr_cClass_DbCallBack 65896UL

/*_* Class: DbCallBack
    Body:  SysBody
    @Aref DbCallBack pwr_sClass_DbCallBack
*/

typedef struct {
  pwr_tString80                       MethodName pwr_dAlignLW;
  pwr_tString40                       MethodArguments[5] pwr_dAlignW;
  pwr_tUInt32                         Method pwr_dAlignW;
  pwr_tUInt32                         Flags pwr_dAlignW;
} pwr_sClass_DbCallBack;

#endif


#ifndef pwr_cClass_DetachedClassVolume
#define pwr_cClass_DetachedClassVolume 66088UL

/*_* Class: DetachedClassVolume
    Body:  SysBody
    @Aref DetachedClassVolume pwr_sClass_DetachedClassVolume
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tObjectIx                       NextOix pwr_dAlignW;
  pwr_tUInt32                         RtVersion pwr_dAlignW;
  pwr_tTime                           RtCreTime pwr_dAlignLW;
  pwr_tString16                       RtCreator pwr_dAlignW;
  pwr_tUInt32                         RtCardinality pwr_dAlignW;
  pwr_tUInt32                         RtBodySize pwr_dAlignW;
  pwr_tObjectIx                       NextCix pwr_dAlignW;
  pwr_tObjectIx                       NextTix[16] pwr_dAlignW;
  pwr_tUInt32                         DvVersion pwr_dAlignW;
} pwr_sClass_DetachedClassVolume;

#endif


#ifndef pwr_cClass_DirectoryVolume
#define pwr_cClass_DirectoryVolume 65968UL

/*_* Class: DirectoryVolume
    Body:  SysBody
    @Aref DirectoryVolume pwr_sClass_DirectoryVolume
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tObjectIx                       NextOix pwr_dAlignW;
  pwr_tUInt32                         RtVersion pwr_dAlignW;
  pwr_tTime                           RtCreTime pwr_dAlignLW;
  pwr_tString16                       RtCreator pwr_dAlignW;
  pwr_tUInt32                         RtCardinality pwr_dAlignW;
  pwr_tUInt32                         RtBodySize pwr_dAlignW;
} pwr_sClass_DirectoryVolume;

#endif


#ifndef pwr_cClass_DocHier
#define pwr_cClass_DocHier 65816UL

/*_* Class: DocHier
    Body:  SysBody
    @Aref DocHier pwr_sClass_DocHier
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
} pwr_sClass_DocHier;

#endif


#ifndef pwr_cClass_DynamicVolume
#define pwr_cClass_DynamicVolume 65936UL

/*_* Class: DynamicVolume
    Body:  SysBody
    @Aref DynamicVolume pwr_sClass_DynamicVolume
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tObjectIx                       NextOix pwr_dAlignW;
  pwr_tUInt32                         RtVersion pwr_dAlignW;
  pwr_tTime                           RtCreTime pwr_dAlignLW;
  pwr_tString16                       RtCreator pwr_dAlignW;
  pwr_tUInt32                         RtCardinality pwr_dAlignW;
  pwr_tUInt32                         RtBodySize pwr_dAlignW;
} pwr_sClass_DynamicVolume;

#endif


#ifndef pwr_cClass_ExternVolume
#define pwr_cClass_ExternVolume 66056UL

/*_* Class: ExternVolume
    Body:  SysBody
    @Aref ExternVolume pwr_sClass_ExternVolume
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
} pwr_sClass_ExternVolume;

#endif


#ifndef pwr_cClass_GraphPlcConnection
#define pwr_cClass_GraphPlcConnection 65744UL

/*_* Class: GraphPlcConnection
    Body:  SysBody
    @Aref GraphPlcConnection pwr_sClass_GraphPlcConnection
*/

typedef struct {
  pwr_tUInt32                         con_type pwr_dAlignLW;
  pwr_tInt32                          arrows pwr_dAlignW;
  pwr_tFloat32                        linewidth pwr_dAlignW;
  pwr_tFloat32                        dashes pwr_dAlignW;
  pwr_tInt32                          fillpattern pwr_dAlignW;
  pwr_tInt32                          color pwr_dAlignW;
  pwr_tInt32                          curvature pwr_dAlignW;
  pwr_tFloat32                        corners pwr_dAlignW;
  pwr_tUInt32                         attributes pwr_dAlignW;
} pwr_sClass_GraphPlcConnection;

#endif


#ifndef pwr_cClass_GraphPlcNode
#define pwr_cClass_GraphPlcNode 65736UL

/*_* Class: GraphPlcNode
    Body:  SysBody
    @Aref GraphPlcNode pwr_sClass_GraphPlcNode
*/

typedef struct {
  pwr_tUInt32                         object_type pwr_dAlignLW;
  pwr_tUInt32                         parameters[4] pwr_dAlignW;
  pwr_tUInt32                         subwindows pwr_dAlignW;
  pwr_tClassId                        subwindow_class[2] pwr_dAlignW;
  pwr_tFloat32                        sw_page_x[2] pwr_dAlignW;
  pwr_tFloat32                        sw_page_y[2] pwr_dAlignW;
  pwr_tUInt32                         graphmethod pwr_dAlignW;
  pwr_tUInt32                         graphindex pwr_dAlignW;
  pwr_tUInt32                         default_mask[2] pwr_dAlignW;
  pwr_tUInt32                         segname_annotation pwr_dAlignW;
  pwr_tBoolean                        rtbody_annotation pwr_dAlignW;
  pwr_tBoolean                        devbody_annotation pwr_dAlignW;
  pwr_tUInt32                         compmethod pwr_dAlignW;
  pwr_tUInt32                         compindex pwr_dAlignW;
  pwr_tUInt32                         tracemethod pwr_dAlignW;
  pwr_tUInt32                         traceindex pwr_dAlignW;
  pwr_tUInt32                         connectmethod pwr_dAlignW;
  pwr_tUInt32                         executeordermethod pwr_dAlignW;
  pwr_tString16                       objname pwr_dAlignW;
  pwr_tString16                       graphname pwr_dAlignW;
  pwr_tString32                       debugpar pwr_dAlignW;
} pwr_sClass_GraphPlcNode;

#endif


#ifndef pwr_cClass_GraphPlcProgram
#define pwr_cClass_GraphPlcProgram 65720UL

/*_* Class: GraphPlcProgram
    Body:  SysBody
    @Aref GraphPlcProgram pwr_sClass_GraphPlcProgram
*/

typedef struct {
  pwr_tUInt32                         plc_type pwr_dAlignLW;
  pwr_tClassId                        subwindow_class pwr_dAlignW;
} pwr_sClass_GraphPlcProgram;

#endif


#ifndef pwr_cClass_GraphPlcWindow
#define pwr_cClass_GraphPlcWindow 65728UL

/*_* Class: GraphPlcWindow
    Body:  SysBody
    @Aref GraphPlcWindow pwr_sClass_GraphPlcWindow
*/

typedef struct {
  pwr_tUInt32                         window_type pwr_dAlignLW;
  pwr_tUInt32                         defaultobjects pwr_dAlignW;
  pwr_tUInt32                         width pwr_dAlignW;
  pwr_tUInt32                         height pwr_dAlignW;
  pwr_tUInt32                         x pwr_dAlignW;
  pwr_tUInt32                         y pwr_dAlignW;
  pwr_tFloat32                        zoom pwr_dAlignW;
  pwr_tObjid                          node_palettelayout pwr_dAlignW;
  pwr_tObjid                          con_palettelayout pwr_dAlignW;
  pwr_tObjid                          trace_palettelayout pwr_dAlignW;
  pwr_tObjid                          sim_palettelayout pwr_dAlignW;
  pwr_tClassId                        defobj_class[5] pwr_dAlignW;
  pwr_tFloat32                        defobj_x[5] pwr_dAlignW;
  pwr_tFloat32                        defobj_y[5] pwr_dAlignW;
  pwr_tUInt32                         compmethod pwr_dAlignW;
  pwr_tUInt32                         compindex pwr_dAlignW;
  pwr_tUInt32                         tracemethod pwr_dAlignW;
  pwr_tUInt32                         traceindex pwr_dAlignW;
  pwr_tUInt32                         executeordermethod pwr_dAlignW;
  pwr_tString16                       objname pwr_dAlignW;
  pwr_tString16                       graphname pwr_dAlignW;
} pwr_sClass_GraphPlcWindow;

#endif


#ifndef pwr_cClass_Group
#define pwr_cClass_Group pwr_eCix_GroupUL

#endif


#ifndef pwr_cClass_GroupRef
#define pwr_cClass_GroupRef pwr_eCix_GroupRefUL

#endif


#ifndef pwr_cClass_Hier
#define pwr_cClass_Hier 66064UL

/*_* Class: Hier
    Body:  SysBody
    @Aref Hier pwr_sClass_Hier
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
} pwr_sClass_Hier;

#endif


#ifndef pwr_cClass_Input
#define pwr_cClass_Input 65584UL

/*_* Class: Input
    Body:  SysBody
    @Aref Input pwr_sClass_Input
*/

typedef struct {
  pwr_tPgmName                        PgmName pwr_dAlignLW;
  pwr_tInt32                          Type pwr_dAlignW;
  pwr_tUInt32                         Offset pwr_dAlignW;
  pwr_tUInt32                         Size pwr_dAlignW;
  pwr_tAdefFlags                      Flags pwr_dAlignW;
  pwr_tUInt32                         Elements pwr_dAlignW;
  pwr_tUInt32                         ParamIndex pwr_dAlignW;
  pwr_tTypeId                         TypeRef pwr_dAlignW;
  pwr_tGraphName                      GraphName pwr_dAlignW;
  pwr_tUInt32                         InputType pwr_dAlignW;
  pwr_tUInt32                         NiNaAnnot pwr_dAlignW;
  pwr_tBoolean                        NiNaCond pwr_dAlignW;
  pwr_tBoolean                        NiNaSegments pwr_dAlignW;
  pwr_tUInt32                         DebAnnot pwr_dAlignW;
  pwr_tUInt32                         ConPointNr pwr_dAlignW;
} pwr_sClass_Input;

#endif


#ifndef pwr_cClass_Intern
#define pwr_cClass_Intern 65600UL

/*_* Class: Intern
    Body:  SysBody
    @Aref Intern pwr_sClass_Intern
*/

typedef struct {
  pwr_tPgmName                        PgmName pwr_dAlignLW;
  pwr_tUInt32                         Type pwr_dAlignW;
  pwr_tUInt32                         Offset pwr_dAlignW;
  pwr_tUInt32                         Size pwr_dAlignW;
  pwr_tAdefFlags                      Flags pwr_dAlignW;
  pwr_tUInt32                         Elements pwr_dAlignW;
  pwr_tUInt32                         ParamIndex pwr_dAlignW;
  pwr_tTypeId                         TypeRef pwr_dAlignW;
  pwr_tGraphName                      GraphName pwr_dAlignW;
  pwr_tUInt32                         InputType pwr_dAlignW;
  pwr_tUInt32                         NiNaAnnot pwr_dAlignW;
  pwr_tBoolean                        NiNaCond pwr_dAlignW;
  pwr_tBoolean                        NiNaSegments pwr_dAlignW;
  pwr_tUInt32                         DebAnnot pwr_dAlignW;
  pwr_tUInt32                         ConPointNr pwr_dAlignW;
} pwr_sClass_Intern;

#endif


#ifndef pwr_cClass_Layout
#define pwr_cClass_Layout pwr_eCix_LayoutUL

#endif


#ifndef pwr_cClass_LibHier
#define pwr_cClass_LibHier 65808UL

/*_* Class: LibHier
    Body:  SysBody
    @Aref LibHier pwr_sClass_LibHier
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
} pwr_sClass_LibHier;

#endif


#ifndef pwr_cClass_Menu
#define pwr_cClass_Menu pwr_eCix_MenuUL

#endif


#ifndef pwr_cClass_MenuButton
#define pwr_cClass_MenuButton 65880UL

/*_* Class: MenuButton
    Body:  SysBody
    @Aref MenuButton pwr_sClass_MenuButton
*/

typedef struct {
  pwr_tString40                       ButtonName pwr_dAlignLW;
  pwr_tString80                       MethodName pwr_dAlignW;
  pwr_tString80                       MethodArguments[5] pwr_dAlignW;
  pwr_tString80                       FilterName pwr_dAlignW;
  pwr_tString80                       FilterArguments[5] pwr_dAlignW;
  pwr_tUInt32                         Method pwr_dAlignW;
  pwr_tUInt32                         Filter pwr_dAlignW;
  pwr_tUInt32                         Flags pwr_dAlignW;
} pwr_sClass_MenuButton;

#endif


#ifndef pwr_cClass_MenuCascade
#define pwr_cClass_MenuCascade 65872UL

/*_* Class: MenuCascade
    Body:  SysBody
    @Aref MenuCascade pwr_sClass_MenuCascade
*/

typedef struct {
  pwr_tString40                       ButtonName pwr_dAlignLW;
  pwr_tString80                       FilterName pwr_dAlignW;
  pwr_tString40                       FilterArguments[5] pwr_dAlignW;
  pwr_tUInt32                         Filter pwr_dAlignW;
} pwr_sClass_MenuCascade;

#endif


#ifndef pwr_cClass_MenuRef
#define pwr_cClass_MenuRef 66016UL

/*_* Class: MenuRef
    Body:  SysBody
    @Aref MenuRef pwr_sClass_MenuRef
*/

typedef struct {
  pwr_tString40                       ButtonName pwr_dAlignLW;
  pwr_tString40                       RefAttribute pwr_dAlignW;
  pwr_tString80                       FilterName pwr_dAlignW;
  pwr_tString40                       FilterArguments[5] pwr_dAlignW;
  pwr_tUInt32                         Filter pwr_dAlignW;
} pwr_sClass_MenuRef;

#endif


#ifndef pwr_cClass_MenuSeparator
#define pwr_cClass_MenuSeparator pwr_eCix_MenuSeparatorUL

#endif


#ifndef pwr_cClass_Method
#define pwr_cClass_Method 66040UL

/*_* Class: Method
    Body:  SysBody
    @Aref Method pwr_sClass_Method
*/

typedef struct {
  pwr_tString80                       MethodName pwr_dAlignLW;
  pwr_tString40                       MethodArguments[5] pwr_dAlignW;
} pwr_sClass_Method;

#endif


#ifndef pwr_cClass_MountObject
#define pwr_cClass_MountObject 65992UL

/*_* Class: MountObject
    Body:  SysBody
    @Aref MountObject pwr_sClass_MountObject
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tObjid                          Object pwr_dAlignW;
} pwr_sClass_MountObject;

#endif


#ifndef pwr_cClass_MountVolume
#define pwr_cClass_MountVolume 65984UL

/*_* Class: MountVolume
    Body:  SysBody
    @Aref MountVolume pwr_sClass_MountVolume
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tVolumeId                       Volume pwr_dAlignW;
  pwr_tUInt32                         VolumeAccess pwr_dAlignW;
  pwr_tUInt32                         MountType pwr_dAlignW;
  pwr_tUInt32                         MountedType pwr_dAlignW;
  pwr_tUInt32                         CacheMaxCount pwr_dAlignW;
  pwr_tUInt32                         CacheMinCount pwr_dAlignW;
  pwr_tUInt32                         CacheCurCount pwr_dAlignW;
} pwr_sClass_MountVolume;

#endif


#ifndef pwr_cClass_Node
#define pwr_cClass_Node 65784UL

/*_* Class: Node
    Body:  SysBody
    @Aref Node pwr_sClass_Node
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tString132                      ErrLogTerm pwr_dAlignW;
  pwr_tString132                      ErrLogFile pwr_dAlignW;
  pwr_tTime                           BootTime pwr_dAlignLW;
  pwr_tTime                           BootVersion pwr_dAlignLW;
  pwr_tUInt32                         BootPlcVersion pwr_dAlignW;
  pwr_tTime                           CurrentVersion pwr_dAlignLW;
  pwr_tUInt32                         CurrentPlcVersion pwr_dAlignW;
  pwr_tUInt32                         Restarts pwr_dAlignW;
  pwr_tTime                           RestartTime pwr_dAlignLW;
  pwr_tDeltaTime                      RestartStallTime pwr_dAlignLW;
  pwr_tTime                           SystemTime pwr_dAlignLW;
  pwr_tNetStatus                      SystemStatus pwr_dAlignW;
  pwr_tStatus                         ProcStatus[80] pwr_dAlignW;
  pwr_tStatus                         ProcMsgSeverity[80] pwr_dAlignW;
  pwr_tString80                       ProcMessage[80] pwr_dAlignW;
  pwr_tObjid                          ProcObject[80] pwr_dAlignW;
  pwr_tTime                           ProcTimeStamp[80] pwr_dAlignLW;
  pwr_tBoolean                        EmergBreakTrue pwr_dAlignW;
  pwr_tEmergBreakSelectEnum           EmergBreakSelect pwr_dAlignW;
} pwr_sClass_Node;

#endif


#ifndef pwr_cClass_NodeHier
#define pwr_cClass_NodeHier 65768UL

/*_* Class: NodeHier
    Body:  SysBody
    @Aref NodeHier pwr_sClass_NodeHier
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tConfigStatusEnum               ConfigurationStatus pwr_dAlignW;
} pwr_sClass_NodeHier;

#endif


#ifndef pwr_cClass_ObjBodyDef
#define pwr_cClass_ObjBodyDef 65568UL

/*_* Class: ObjBodyDef
    Body:  SysBody
    @Aref ObjBodyDef pwr_sClass_ObjBodyDef
*/

typedef struct {
  pwr_tPgmName                        StructName pwr_dAlignLW;
  pwr_tUInt32                         NumOfParams pwr_dAlignW;
  pwr_tUInt32                         Size pwr_dAlignW;
  pwr_tObjectIx                       NextAix pwr_dAlignW;
  pwr_tObjBodyDefFlags                Flags pwr_dAlignW;
} pwr_sClass_ObjBodyDef;

#endif


#ifndef pwr_cClass_Object
#define pwr_cClass_Object 65888UL

/*_* Class: Object
    Body:  SysBody
    @Aref Object pwr_sClass_Object
*/

typedef struct {
  pwr_tObjName                        Name pwr_dAlignLW;
} pwr_sClass_Object;

#endif


#ifndef pwr_cClass_ObjXRef
#define pwr_cClass_ObjXRef 65616UL

/*_* Class: ObjXRef
    Body:  SysBody
    @Aref ObjXRef pwr_sClass_ObjXRef
*/

typedef struct {
  pwr_tPgmName                        PgmName pwr_dAlignLW;
  pwr_tInt32                          Type pwr_dAlignW;
  pwr_tUInt32                         Offset pwr_dAlignW;
  pwr_tUInt32                         Size pwr_dAlignW;
  pwr_tAdefFlags                      Flags pwr_dAlignW;
  pwr_tUInt32                         Elements pwr_dAlignW;
  pwr_tUInt32                         ParamIndex pwr_dAlignW;
  pwr_tXRef                           Identity pwr_dAlignW;
  pwr_tXRef                           Source pwr_dAlignW;
  pwr_tXRef                           Target pwr_dAlignW;
  pwr_tUInt32                         XRefType pwr_dAlignW;
  pwr_tObjName                        SourceAttribute pwr_dAlignW;
  pwr_tObjName                        TargetAttribute pwr_dAlignW;
} pwr_sClass_ObjXRef;

#endif


#ifndef pwr_cClass_Output
#define pwr_cClass_Output 65592UL

/*_* Class: Output
    Body:  SysBody
    @Aref Output pwr_sClass_Output
*/

typedef struct {
  pwr_tPgmName                        PgmName pwr_dAlignLW;
  pwr_tUInt32                         Type pwr_dAlignW;
  pwr_tUInt32                         Offset pwr_dAlignW;
  pwr_tUInt32                         Size pwr_dAlignW;
  pwr_tAdefFlags                      Flags pwr_dAlignW;
  pwr_tUInt32                         Elements pwr_dAlignW;
  pwr_tUInt32                         ParamIndex pwr_dAlignW;
  pwr_tTypeId                         TypeRef pwr_dAlignW;
  pwr_tGraphName                      GraphName pwr_dAlignW;
  pwr_tUInt32                         InputType pwr_dAlignW;
  pwr_tUInt32                         NiNaAnnot pwr_dAlignW;
  pwr_tBoolean                        NiNaCond pwr_dAlignW;
  pwr_tBoolean                        NiNaSegments pwr_dAlignW;
  pwr_tUInt32                         DebAnnot pwr_dAlignW;
  pwr_tUInt32                         ConPointNr pwr_dAlignW;
} pwr_sClass_Output;

#endif


#ifndef pwr_cClass_PlantHier
#define pwr_cClass_PlantHier 65672UL

/*_* Class: PlantHier
    Body:  SysBody
    @Aref PlantHier pwr_sClass_PlantHier
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_sAttrRef                        DefGraph pwr_dAlignW;
  pwr_sAttrRef                        DefTrend pwr_dAlignW;
  pwr_tString40                       HelpTopic pwr_dAlignW;
  pwr_tURL                            DataSheet pwr_dAlignW;
  pwr_tURL                            CircuitDiagram pwr_dAlignW;
  pwr_tURL                            Photo pwr_dAlignW;
  pwr_tConfigStatusEnum               ConfigurationStatus pwr_dAlignW;
} pwr_sClass_PlantHier;

#endif


#ifndef pwr_cClass_PlcConnection
#define pwr_cClass_PlcConnection 65704UL

/*_* Class: PlcConnection
    Body:  SysBody
    @Aref PlcConnection pwr_sClass_PlcConnection
*/

typedef struct {
  pwr_tObjid                          oid pwr_dAlignLW;
  pwr_tUInt32                         object_type pwr_dAlignW;
  pwr_tClassId                        cid pwr_dAlignW;
  pwr_tUInt32                         curvature pwr_dAlignW;
  pwr_tUInt32                         drawtype pwr_dAlignW;
  pwr_tUInt32                         attributes pwr_dAlignW;
  pwr_tUInt32                         refnr pwr_dAlignW;
  pwr_tUInt32                         source_point pwr_dAlignW;
  pwr_tObjid                          source_oid pwr_dAlignW;
  pwr_tUInt32                         dest_point pwr_dAlignW;
  pwr_tObjid                          dest_oid pwr_dAlignW;
  pwr_tUInt32                         point_count pwr_dAlignW;
  pwr_sPoint                          point[10] pwr_dAlignLW;
  pwr_tObjid                          woid pwr_dAlignLW;
} pwr_sClass_PlcConnection;

#endif


#ifndef pwr_cClass_PlcNode
#define pwr_cClass_PlcNode 65696UL

/*_* Class: PlcNode
    Body:  SysBody
    @Aref PlcNode pwr_sClass_PlcNode
*/

typedef struct {
  pwr_tUInt32                         object_type pwr_dAlignLW;
  pwr_tClassId                        cid pwr_dAlignW;
  pwr_tObjid                          oid pwr_dAlignW;
  pwr_tFloat32                        x pwr_dAlignW;
  pwr_tFloat32                        y pwr_dAlignW;
  pwr_tFloat32                        width pwr_dAlignW;
  pwr_tFloat32                        heigth pwr_dAlignW;
  pwr_tObjid                          woid pwr_dAlignW;
  pwr_tObjid                          subwind_oid[2] pwr_dAlignW;
  pwr_tUInt32                         subwindow pwr_dAlignW;
  pwr_tUInt32                         graphtype pwr_dAlignW;
  pwr_tUInt32                         mask[3] pwr_dAlignW;
  pwr_tUInt32                         compdirection pwr_dAlignW;
  pwr_tUInt32                         nodewidth pwr_dAlignW;
} pwr_sClass_PlcNode;

#endif


#ifndef pwr_cClass_PlcProgram
#define pwr_cClass_PlcProgram 65680UL

/*_* Class: PlcProgram
    Body:  SysBody
    @Aref PlcProgram pwr_sClass_PlcProgram
*/

typedef struct {
  pwr_tObjid                          oid pwr_dAlignLW;
  pwr_tUInt32                         object_type pwr_dAlignW;
  pwr_tClassId                        cid pwr_dAlignW;
  pwr_tUInt32                         defnamecount[300] pwr_dAlignW;
  pwr_tObjid                          reset_oid pwr_dAlignW;
  pwr_tUInt32                         connamecount pwr_dAlignW;
  pwr_tObjid                          woid pwr_dAlignW;
} pwr_sClass_PlcProgram;

#endif


#ifndef pwr_cClass_PlcWindow
#define pwr_cClass_PlcWindow 65688UL

/*_* Class: PlcWindow
    Body:  SysBody
    @Aref PlcWindow pwr_sClass_PlcWindow
*/

typedef struct {
  pwr_tObjid                          oid pwr_dAlignLW;
  pwr_tUInt32                         object_type pwr_dAlignW;
  pwr_tClassId                        cid pwr_dAlignW;
  pwr_tFloat32                        x pwr_dAlignW;
  pwr_tFloat32                        y pwr_dAlignW;
  pwr_tFloat32                        width pwr_dAlignW;
  pwr_tFloat32                        heigth pwr_dAlignW;
  pwr_tFloat32                        zoom pwr_dAlignW;
  pwr_tInt32                          x_root pwr_dAlignW;
  pwr_tInt32                          y_root pwr_dAlignW;
  pwr_tObjid                          poid pwr_dAlignW;
  pwr_tUInt32                         compobjcount pwr_dAlignW;
  pwr_tUInt32                         refconcount pwr_dAlignW;
  pwr_tUInt32                         subwindowindex pwr_dAlignW;
} pwr_sClass_PlcWindow;

#endif


#ifndef pwr_cClass_AnyPoint
#define pwr_cClass_AnyPoint 65712UL

/*_* Class: Point
    Body:  SysBody
    @Aref Point pwr_sClass_AnyPoint
*/

typedef struct {
  pwr_tFloat32                        x pwr_dAlignLW;
  pwr_tFloat32                        y pwr_dAlignW;
} pwr_sClass_AnyPoint;

#endif


#ifndef pwr_cClass_RootVolume
#define pwr_cClass_RootVolume 65912UL

/*_* Class: RootVolume
    Body:  SysBody
    @Aref RootVolume pwr_sClass_RootVolume
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tObjectIx                       NextOix pwr_dAlignW;
  pwr_tUInt32                         RtVersion pwr_dAlignW;
  pwr_tTime                           RtCreTime pwr_dAlignLW;
  pwr_tString16                       RtCreator pwr_dAlignW;
  pwr_tUInt32                         RtCardinality pwr_dAlignW;
  pwr_tUInt32                         RtBodySize pwr_dAlignW;
  pwr_tOpSysMask                      OperatingSystem pwr_dAlignW;
  pwr_tTime                           Modified pwr_dAlignLW;
  pwr_tConfigStatusEnum               ConfigurationStatus pwr_dAlignW;
} pwr_sClass_RootVolume;

#endif


#ifndef pwr_cClass_RtMenu
#define pwr_cClass_RtMenu pwr_eCix_RtMenuUL

#endif


#ifndef pwr_cClass_RtMethod
#define pwr_cClass_RtMethod pwr_eCix_RtMethodUL

#endif


#ifndef pwr_cClass_Security
#define pwr_cClass_Security 66080UL

/*_* Class: Security
    Body:  SysBody
    @Aref Security pwr_sClass_Security
*/

typedef struct {
  pwr_tPrivMask                       DefaultWebPriv pwr_dAlignLW;
  pwr_tPrivMask                       DefaultXttPriv pwr_dAlignW;
  pwr_tBoolean                        XttUseOpsysUser pwr_dAlignW;
  pwr_tString80                       WebSystemGroup pwr_dAlignW;
} pwr_sClass_Security;

#endif


#ifndef pwr_cClass_SharedVolume
#define pwr_cClass_SharedVolume 65928UL

/*_* Class: SharedVolume
    Body:  SysBody
    @Aref SharedVolume pwr_sClass_SharedVolume
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tObjectIx                       NextOix pwr_dAlignW;
  pwr_tUInt32                         RtVersion pwr_dAlignW;
  pwr_tTime                           RtCreTime pwr_dAlignLW;
  pwr_tString16                       RtCreator pwr_dAlignW;
  pwr_tUInt32                         RtCardinality pwr_dAlignW;
  pwr_tUInt32                         RtBodySize pwr_dAlignW;
  pwr_tTime                           Modified pwr_dAlignLW;
  pwr_tConfigStatusEnum               ConfigurationStatus pwr_dAlignW;
} pwr_sClass_SharedVolume;

#endif


#ifndef pwr_cClass_SubVolume
#define pwr_cClass_SubVolume 65920UL

/*_* Class: SubVolume
    Body:  SysBody
    @Aref SubVolume pwr_sClass_SubVolume
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tObjectIx                       NextOix pwr_dAlignW;
  pwr_tUInt32                         RtVersion pwr_dAlignW;
  pwr_tTime                           RtCreTime pwr_dAlignLW;
  pwr_tString16                       RtCreator pwr_dAlignW;
  pwr_tUInt32                         RtCardinality pwr_dAlignW;
  pwr_tUInt32                         RtBodySize pwr_dAlignW;
  pwr_tOpSysMask                      OperatingSystem pwr_dAlignW;
  pwr_tTime                           Modified pwr_dAlignLW;
  pwr_tConfigStatusEnum               ConfigurationStatus pwr_dAlignW;
} pwr_sClass_SubVolume;

#endif


#ifndef pwr_cClass_System
#define pwr_cClass_System 65800UL

/*_* Class: System
    Body:  SysBody
    @Aref System pwr_sClass_System
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tString80                       SystemName pwr_dAlignW;
  pwr_tString80                       SystemGroup pwr_dAlignW;
} pwr_sClass_System;

#endif


#ifndef pwr_cClass_SystemVolume
#define pwr_cClass_SystemVolume 65944UL

/*_* Class: SystemVolume
    Body:  SysBody
    @Aref SystemVolume pwr_sClass_SystemVolume
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tObjectIx                       NextOix pwr_dAlignW;
  pwr_tUInt32                         RtVersion pwr_dAlignW;
  pwr_tTime                           RtCreTime pwr_dAlignLW;
  pwr_tString16                       RtCreator pwr_dAlignW;
  pwr_tUInt32                         RtCardinality pwr_dAlignW;
  pwr_tUInt32                         RtBodySize pwr_dAlignW;
} pwr_sClass_SystemVolume;

#endif


#ifndef pwr_cClass_Type
#define pwr_cClass_Type 65552UL

/*_* Class: Type
    Body:  SysBody
    @Aref Type pwr_sClass_Type
*/

typedef struct {
  pwr_tInt32                          Type pwr_dAlignLW;
  pwr_tInt32                          Size pwr_dAlignW;
} pwr_sClass_Type;

#endif


#ifndef pwr_cClass_TypeDef
#define pwr_cClass_TypeDef 65560UL

/*_* Class: TypeDef
    Body:  SysBody
    @Aref TypeDef pwr_sClass_TypeDef
*/

typedef struct {
  pwr_tInt32                          Type pwr_dAlignLW;
  pwr_tInt32                          Size pwr_dAlignW;
  pwr_tTypeId                         TypeRef pwr_dAlignW;
  pwr_tInt32                          Elements pwr_dAlignW;
  pwr_tPgmName                        PgmName pwr_dAlignW;
} pwr_sClass_TypeDef;

#endif


#ifndef pwr_cClass_TypeHier
#define pwr_cClass_TypeHier pwr_eCix_TypeHierUL

#endif


#ifndef pwr_cClass_Value
#define pwr_cClass_Value 66032UL

/*_* Class: Value
    Body:  SysBody
    @Aref Value pwr_sClass_Value
*/

typedef struct {
  pwr_tString80                       Text pwr_dAlignLW;
  pwr_tString32                       PgmName pwr_dAlignW;
  pwr_tInt32                          Value pwr_dAlignW;
} pwr_sClass_Value;

#endif


#ifndef pwr_cClass_VolatileVolume
#define pwr_cClass_VolatileVolume 66008UL

/*_* Class: VolatileVolume
    Body:  SysBody
    @Aref VolatileVolume pwr_sClass_VolatileVolume
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tObjectIx                       NextOix pwr_dAlignW;
} pwr_sClass_VolatileVolume;

#endif


#ifndef pwr_cClass_WorkBenchVolume
#define pwr_cClass_WorkBenchVolume 65960UL

/*_* Class: WorkBenchVolume
    Body:  SysBody
    @Aref WorkBenchVolume pwr_sClass_WorkBenchVolume
*/

typedef struct {
  pwr_tString80                       Description pwr_dAlignLW;
  pwr_tObjectIx                       NextOix pwr_dAlignW;
  pwr_tUInt32                         RtVersion pwr_dAlignW;
  pwr_tTime                           RtCreTime pwr_dAlignLW;
  pwr_tString16                       RtCreator pwr_dAlignW;
  pwr_tUInt32                         RtCardinality pwr_dAlignW;
  pwr_tUInt32                         RtBodySize pwr_dAlignW;
} pwr_sClass_WorkBenchVolume;

#endif

#endif
